// <auto-generated />
namespace CMFLMS.Migrations.IdentityMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _5Create : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_5Create));
        
        string IMigrationMetadata.Id
        {
            get { return "201803131227367_5Create"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
