// <auto-generated />
namespace CMFLMS.Migrations.LibraryMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Fabric_Two_Primary_Keys_18Crate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Fabric_Two_Primary_Keys_18Crate));
        
        string IMigrationMetadata.Id
        {
            get { return "201803200502025_Fabric_Two_Primary_Keys_18Crate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
