// <auto-generated />
namespace CMFLMS.Migrations.LibraryMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _14Create : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_14Create));
        
        string IMigrationMetadata.Id
        {
            get { return "201802281212278_14Create"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
