// <auto-generated />
namespace CMFLMS.Migrations.LibraryMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UsersWithFactory_Maping_Table_Added_Date_20Crate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UsersWithFactory_Maping_Table_Added_Date_20Crate));
        
        string IMigrationMetadata.Id
        {
            get { return "201803201001034_UsersWithFactory_Maping_Table_Added_Date_20Crate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
