// <auto-generated />
namespace CMFLMS.Migrations.LibraryMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TPLength : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TPLength));
        
        string IMigrationMetadata.Id
        {
            get { return "201903190711493_TPLength"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
